language: php
php:
  - 5.4
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y valgrind
before_script: phpize
script:
  - ./configure
  - make
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test
