language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5-dev
  - sudo apt-get install -y php5-cli
before_script: phpize
script:
  - ./configure
  - perl -i -pe 's/\-\@if/\@if/' Makefile
  - make
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test
